-- CreateTable
CREATE TABLE "__seed_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "executed_at" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE UNIQUE INDEX "__seed_history_name_key" ON "__seed_history"("name");
