 
// ⚠️ AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/gen-seeds-index.ts

import { PrismaClient } from '../../prisma/generated/client';
import * as seed_2025_12_22_initial from './2025_12_22_initial';

export const seedRecords: Record<string, (prisma: PrismaClient) => Promise<void>> = {
  '2025_12_22_initial': seed_2025_12_22_initial.seed,
};
