import type { PackageDefinition } from './schemas';

const GITHUB = 'https://github.com/royfw/rfjs';

const npmUrl = (name: string) => `https://www.npmjs.com/package/${name}`;

export const packageRegistry: PackageDefinition[] = [
  {
    name: '@rfjs/data-filter',
    description: 'Filter in-memory data with JSONPath-addressed conditions.',
    status: 'ready',
    href: '/packages/data-filter',
    npm: npmUrl('@rfjs/data-filter'),
    github: GITHUB,
    tags: ['filter', 'jsonpath'],
    relatedTools: ['data-filter-tester', 'data-filter-builder'],
  },
  {
    name: '@rfjs/data-transform',
    description: 'Data type transformation utilities (string/number/boolean/date).',
    status: 'ready',
    href: '/packages/data-transform',
    npm: npmUrl('@rfjs/data-transform'),
    github: GITHUB,
    tags: ['transform', 'types'],
    relatedTools: ['type-converter', 'object-transformer'],
  },
  {
    name: '@rfjs/data-label',
    description:
      'Compose display label strings from data paths, value maps, and templates.',
    status: 'preview',
    href: '/packages/data-label',
    github: GITHUB,
    tags: ['label', 'template'],
  },
  {
    name: '@rfjs/jsonb-query',
    description: 'PostgreSQL JSONB query builder from filter metadata.',
    status: 'preview',
    href: '/packages/jsonb-query',
    github: GITHUB,
    tags: ['postgres', 'jsonb'],
    relatedTools: ['jsonb-query-generator'],
  },
  {
    name: '@rfjs/jwt',
    description: 'JWT sign/verify/decode helper.',
    status: 'ready',
    href: '/packages/jwt',
    npm: npmUrl('@rfjs/jwt'),
    github: GITHUB,
    tags: ['jwt', 'auth'],
    relatedTools: ['jwt-decoder'],
  },
  {
    name: '@rfjs/mongo-query',
    description: 'MongoDB query builder from filter metadata.',
    status: 'ready',
    href: '/packages/mongo-query',
    npm: npmUrl('@rfjs/mongo-query'),
    github: GITHUB,
    tags: ['mongodb', 'query'],
    relatedTools: ['mongo-query-generator'],
  },
  {
    name: '@rfjs/object-utils',
    description: 'Object manipulation utilities (flatten, paths, merge).',
    status: 'ready',
    href: '/packages/object-utils',
    npm: npmUrl('@rfjs/object-utils'),
    github: GITHUB,
    tags: ['object', 'flatten'],
    relatedTools: ['object-flatten', 'object-transformer'],
  },
  {
    name: '@rfjs/pg-toolkit',
    description: 'PostgreSQL admin utilities (seed history, DB/schema creation).',
    status: 'ready',
    href: '/packages/pg-toolkit',
    npm: npmUrl('@rfjs/pg-toolkit'),
    github: GITHUB,
    tags: ['postgres', 'admin'],
  },
  {
    name: '@rfjs/retry',
    description: 'Retry helper with configurable delay.',
    status: 'ready',
    href: '/packages/retry',
    npm: npmUrl('@rfjs/retry'),
    github: GITHUB,
    tags: ['retry', 'async'],
  },
  {
    name: '@rfjs/tpl-toolkit',
    description: 'Shared config factories for rfjs project templates.',
    status: 'ready',
    href: '/packages/tpl-toolkit',
    npm: npmUrl('@rfjs/tpl-toolkit'),
    github: GITHUB,
    tags: ['config', 'templates'],
  },
];
