import type { ToolDefinition } from './schemas';

export const toolRegistry: ToolDefinition[] = [
  {
    id: 'object-flatten',
    category: 'transform',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/object-utils'],
    tags: ['object', 'flatten'],
  },
  {
    id: 'type-converter',
    category: 'transform',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/data-transform'],
    tags: ['convert', 'types'],
  },
  {
    id: 'data-filter-tester',
    category: 'filter',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/data-filter'],
    tags: ['jsonpath', 'filter'],
  },
  {
    id: 'jwt-decoder',
    category: 'inspect',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/jwt'],
    tags: ['jwt', 'decode'],
  },
  {
    id: 'jsonb-query-generator',
    category: 'query',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/jsonb-query'],
    tags: ['postgres', 'jsonb', 'sql'],
  },
  {
    id: 'mongo-query-generator',
    category: 'query',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/mongo-query'],
    tags: ['mongodb', 'query'],
  },
  {
    id: 'data-filter-builder',
    category: 'filter',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/data-filter', '@rfjs/filter-builder'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'jsonb-query-builder',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/jsonb-query', '@rfjs/filter-builder'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'sql-filter-builder',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/sql-filter', '@rfjs/filter-builder'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'mongo-query-builder',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/mongo-query', '@rfjs/filter-builder'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'es-query-builder',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/es-query', '@rfjs/filter-builder'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'es-client-demo',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/es-client', '@rfjs/es-query'],
    tags: ['client', 'playground'],
  },
  {
    id: 'pg-filter-builder',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/pg-filter', '@rfjs/filter-builder'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'form-builder',
    category: 'generator',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/form-builder'],
    tags: ['form', 'builder', 'config'],
  },
  {
    id: 'form-canvas',
    category: 'generator',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/form-builder'],
    tags: ['form', 'builder', 'canvas', '2d'],
  },
  {
    id: 'object-transformer',
    category: 'transform',
    surface: 'workbench',
    status: 'planned',
    relatedPackages: ['@rfjs/object-utils', '@rfjs/data-transform'],
    tags: ['object', 'playground'],
  },
];
