import type { ToolDefinition } from './schemas';

export const toolRegistry: ToolDefinition[] = [
  {
    id: 'object-flatten',
    category: 'transform',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/object-utils'],
    tags: ['object', 'flatten'],
  },
  {
    id: 'type-converter',
    category: 'transform',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/data-transform'],
    tags: ['convert', 'types'],
  },
  {
    id: 'data-filter-tester',
    category: 'filter',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/data-filter'],
    tags: ['jsonpath', 'filter'],
  },
  {
    id: 'jwt-decoder',
    category: 'inspect',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/jwt'],
    tags: ['jwt', 'decode'],
  },
  {
    id: 'jsonb-query-generator',
    category: 'query',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/jsonb-query'],
    tags: ['postgres', 'jsonb', 'sql'],
  },
  {
    id: 'query-builder',
    category: 'query',
    surface: 'web',
    status: 'preview',
    relatedPackages: ['@rfjs/jsonb-query', '@rfjs/data-filter', '@rfjs/pg-filter'],
    tags: ['builder', 'jsonb', 'sql', 'nested'],
  },
  {
    id: 'mongo-query-generator',
    category: 'query',
    surface: 'web',
    status: 'planned',
    relatedPackages: ['@rfjs/mongo-query'],
    tags: ['mongodb', 'query'],
  },
  {
    id: 'data-filter-builder',
    category: 'filter',
    surface: 'workbench',
    status: 'planned',
    relatedPackages: ['@rfjs/data-filter'],
    tags: ['builder', 'playground'],
  },
  {
    id: 'object-transformer',
    category: 'transform',
    surface: 'workbench',
    status: 'planned',
    relatedPackages: ['@rfjs/object-utils', '@rfjs/data-transform'],
    tags: ['object', 'playground'],
  },
];
