 
// ⚠️ AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/gen-migrations-index.ts

import type { Migration } from 'kysely';
import * as m2021_09_18_06_54_59_create_user from './2021_09_18_06_54_59_create_user';
import * as m2021_09_18_14_05_20_create_refresh_token from './2021_09_18_14_05_20_create_refresh_token';
import * as m2021_09_18_18_22_45_create_sign_in_method from './2021_09_18_18_22_45_create_sign_in_method';

export const migrations: Record<string, Migration> = {
  '2021_09_18_06_54_59_create_user': m2021_09_18_06_54_59_create_user,
  '2021_09_18_14_05_20_create_refresh_token': m2021_09_18_14_05_20_create_refresh_token,
  '2021_09_18_18_22_45_create_sign_in_method': m2021_09_18_18_22_45_create_sign_in_method,
};
