import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

type Options = {
  seedsDir: string; // e.g. src/seeds
  outFile: string; // e.g. src/seeds/index.ts
};

const DEFAULTS: Options = {
  seedsDir: 'src/seeds',
  outFile: 'src/seeds/index.ts',
};

function isMigrationFile(file: string) {
  // keep .ts but exclude index & typings & tests
  if (!file.endsWith('.ts')) return false;
  if (file === 'index.ts') return false;
  if (file.endsWith('.d.ts')) return false;
  if (file.endsWith('.test.ts') || file.endsWith('.spec.ts')) return false;
  return true;
}

// Make a safe TS identifier from file name
function toIdentifier(baseName: string) {
  // 2021_09_18_06_54_59_create_user -> m2021_09_18_06_54_59_create_user
  // also replace invalid chars with _
  const cleaned = baseName.replace(/[^a-zA-Z0-9_]/g, '_');
  return cleaned.match(/^[0-9]/) ? `seed_${cleaned}` : cleaned;
}

async function main() {
  const opts: Options = {
    seedsDir: process.argv[2] ?? DEFAULTS.seedsDir,
    outFile: process.argv[3] ?? DEFAULTS.outFile,
  };

  const absSeedsDir = path.resolve(process.cwd(), opts.seedsDir);
  const absOutFile = path.resolve(process.cwd(), opts.outFile);

  const entries = await fs.readdir(absSeedsDir, { withFileTypes: true });
  const files = entries
    .filter((e) => e.isFile())
    .map((e) => e.name)
    .filter(isMigrationFile)
    .sort((a, b) => a.localeCompare(b));

  if (files.length === 0) {
    throw new Error(`No migration files found in ${opts.seedsDir}`);
  }

  const imports = files.map((file) => {
    const base = file.replace(/\.ts$/, '');
    const ident = toIdentifier(base);
    return { file, base, ident };
  });

  const content = `/* eslint-disable */
// ⚠️ AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/gen-seeds-index.ts

import { DataSource } from 'typeorm';
${imports.map((i) => `import * as ${i.ident} from './${i.base}';`).join('\n')}

export const seedRecords: Record<string, (db: DataSource) => Promise<void>> = {
${imports.map((i) => `  '${i.base}': ${i.ident}.seed,`).join('\n')}
};
`;

  await fs.writeFile(absOutFile, content, 'utf8');
  // optional: print a friendly log
  console.log(`Generated ${opts.outFile} with ${files.length} seeds.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
